[package]
name = "rustica-agent"
version = "0.1.0"
authors = ["Mitchell Grenier <mitchell@confurious.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.3"
prost = "0.6"
futures-core = "0.3"
futures-util = "0.3"
tokio = { version = "0.2", features = ["full"] }

base64 = "0.12.1"
byteorder = "*"
hex = "*"
log = "*"
sha2 = "0.9.2"
ring = "0.16.9"
rustica-sshkey = {path = "../rustica-sshkey"}
yubikey-piv = {version = "0.1.0", features = ["untested"]}

[build-dependencies]
tonic-build = "0.3"